/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CCPay } from "./CCPay";
export * as factories from "./factories";
export { CCPay__factory } from "./factories/CCPay__factory";
